<a href="https://colab.research.google.com/github/JoshuaUgarte/CLASETHC/blob/Trabajo-en-clase/EXAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#CALCULAR LA TRAZA DE UNA MATRIZ 3X3
import numpy as np

def calcular_traza():
    # primero creamos una matriz 3x3 llena de ceros
    matriz = np.zeros((3, 3))

    # solicitamos al usuario que introduzca los valores de la matriz
    print("Hola! Vamos a calcular la traza de una matriz 3x3.")
    for fila in range(3):
        for columna in range(3):
            valor = float(input(f"Ingrese el valor en la posición ({fila + 1}, {columna + 1}): "))
            matriz[fila, columna] = valor

    # aqui se calcula la traza de la matriz
    traza = np.trace(matriz)

    # se imprime la matriz
    print("La matriz que has ingresado es la siguiente:")
    print(matriz)

    # se imrpime la traza
    print(f"La traza de la matriz es: {traza}")

# llamamos a la función
calcular_traza()


Hola! Vamos a calcular la traza de una matriz 3x3.
Ingrese el valor en la posición (1, 1): 1
Ingrese el valor en la posición (1, 2): 2
Ingrese el valor en la posición (1, 3): 3
Ingrese el valor en la posición (2, 1): 1
Ingrese el valor en la posición (2, 2): 2
Ingrese el valor en la posición (2, 3): 3
Ingrese el valor en la posición (3, 1): 1
Ingrese el valor en la posición (3, 2): 2
Ingrese el valor en la posición (3, 3): 3
La matriz que has ingresado es la siguiente:
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
La traza de la matriz es: 6.0


In [9]:
#ENCONTRAR EL MAXIMO Y MINIMO DE UNA FUNCION
import numpy as np

def encontrar_maximo_minimo():
    # aqui se crea una matriz vacía de 3x3
    matriz = np.zeros((3, 3))

    # se solicita al usuario que ingrese los valores de la matriz
    for fila in range(3):
        for columna in range(3):
            valor = float(input(f"Por favor, ingresa el valor en la posición ({fila+1}, {columna+1}): "))
            matriz[fila, columna] = valor

    # encontramos el valor máximo y mínimo en la matriz
    maximo = np.max(matriz)
    minimo = np.min(matriz)

    print("La matriz que has ingresado es la siguiente:")
    print(matriz)
    print(f"El valor máximo en la matriz es: {maximo}")
    print(f"El valor mínimo en la matriz es: {minimo}")

# se llama a la función
encontrar_maximo_minimo()


Por favor, ingresa el valor en la posición (1, 1): 1
Por favor, ingresa el valor en la posición (1, 2): 2
Por favor, ingresa el valor en la posición (1, 3): 3
Por favor, ingresa el valor en la posición (2, 1): 1
Por favor, ingresa el valor en la posición (2, 2): 2
Por favor, ingresa el valor en la posición (2, 3): 3
Por favor, ingresa el valor en la posición (3, 1): 1
Por favor, ingresa el valor en la posición (3, 2): 2
Por favor, ingresa el valor en la posición (3, 3): 3
La matriz que has ingresado es la siguiente:
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
El valor máximo en la matriz es: 3.0
El valor mínimo en la matriz es: 1.0


In [12]:
#CALCULAR LA POTENCIA DE UNA MATRIZ
import numpy as np

def calcular_potencia_de_matriz():
    # primero creamos una matriz vacía de 3x3
    matriz = np.zeros((3, 3))

    # le pedimos al usuario que ingrese los valores de la matriz
    for fila in range(3):
        for columna in range(3):
            valor = float(input(f"Por favor, ingresa el valor en la posición ({fila+1}, {columna+1}): "))
            matriz[fila, columna] = valor

    # le edimos al usuario que ingrese la potencia deseada
    potencia = int(input("Por favor, introduce la potencia a la que deseas elevar la matriz: "))

    # ahora calculamos la matriz elevada a la potencia requerida
    resultado = np.linalg.matrix_power(matriz, potencia)

    print("La matriz que has ingresado es la siguiente:")
    print(matriz)
    print(f"La matriz elevada a la potencia {potencia} es la siguiente:")
    print(resultado)

# para concluir llamamos a la función
calcular_potencia_de_matriz()


Por favor, ingresa el valor en la posición (1, 1): 1
Por favor, ingresa el valor en la posición (1, 2): 2
Por favor, ingresa el valor en la posición (1, 3): 3
Por favor, ingresa el valor en la posición (2, 1): 1
Por favor, ingresa el valor en la posición (2, 2): 2
Por favor, ingresa el valor en la posición (2, 3): 3
Por favor, ingresa el valor en la posición (3, 1): 1
Por favor, ingresa el valor en la posición (3, 2): 2
Por favor, ingresa el valor en la posición (3, 3): 3
Por favor, introduce la potencia a la que deseas elevar la matriz: 2
La matriz que has ingresado es la siguiente:
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
La matriz elevada a la potencia 2 es la siguiente:
[[ 6. 12. 18.]
 [ 6. 12. 18.]
 [ 6. 12. 18.]]
